# Case 0. Learning basics 
**Neural Networks for Machine Learning Applications**<br>
11.01.2023<br>
Julian Marco Soliveres<br>
[Information Technology, Bachelor's Degree](https://www.metropolia.fi/en/academics/bachelors-degrees/information-technology)<br>
[Metropolia University of Applied Sciences](https://www.metropolia.fi/en)

- **v3**: Simplified version based on discussion with JK.
- **v4**: Added conversion of labels [to_categorical](https://www.tensorflow.org/api_docs/python/tf/keras/utils/to_categorical) and changed the loss function to [categorical crossentropy](https://www.tensorflow.org/api_docs/python/tf/keras/metrics/categorical_crossentropy).
- **v5**: Changes in instructions wordings.

## 1. Introduction

This nootbook was created to do the assignament "Case 0: Learning the basics".

## 2. Setup

The library used here was tensorflow.

In [1]:
!pip install tensorflow

  Using cached tensorflow-2.11.0-cp39-cp39-win_amd64.whl (1.9 kB)
     ------------------------------------- 266.3/266.3 MB 10.2 MB/s eta 0:00:00
     ---------------------------------------- 1.7/1.7 MB 104.7 MB/s eta 0:00:00
     ---------------------------------------- 439.2/439.2 kB ? eta 0:00:00
     ---------------------------------------- 65.5/65.5 kB 3.5 MB/s eta 0:00:00
     ---------------------------------------- 126.5/126.5 kB ? eta 0:00:00
     --------------------------------------- 23.2/23.2 MB 40.9 MB/s eta 0:00:00
     ---------------------------------------- 1.5/1.5 MB 92.3 MB/s eta 0:00:00
     ---------------------------------------- 57.5/57.5 kB ? eta 0:00:00
     ---------------------------------------- 6.0/6.0 MB 63.6 MB/s eta 0:00:00
     ------------------------------------- 895.9/895.9 kB 55.4 MB/s eta 0:00:00
     ---------------------------------------- 3.7/3.7 MB 120.3 MB/s eta 0:00:00
     ------------------------------------- 781.3/781.3 kB 48.2 MB/s eta 0

In [2]:
import tensorflow as tf
print(f'tensorflow: {tf.__version__}')

tensorflow: 2.11.0


## 3. Dataset

The **mnist** is a dataset from the library tensorflow of 60,000 28x28 grayscale images of the 10 digits, along with a test set of 10,000 images. <br>
**x_train** is a uint8 NumPy array of grayscale image data with shapes (60000, 28, 28), containing the training data. <br>
**y_train** is a uint8 NumPy array of digit labels (integers in range 0-9) with shape (60000,) for the training data. <br>
**x_test** is a  uint8 NumPy array of grayscale image data with shapes (10000, 28, 28), containing the test data. Pixel values range from 0 to 255. <br>
**y_test** is a uint8 NumPy array of digit labels (integers in range 0-9) with shape (10000,) for the test data.

In [3]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()

11490434/11490434 [==============================] - 0s 0us/step


In [4]:
print(f'x_train: shape {x_train.shape} and ndim {x_train.ndim}')
print(f'x_test:  shape {x_test.shape} and ndim {x_test.ndim}')

print(f'y_train: shape {y_train.shape} and ndim {y_train.ndim}')
print(f'y_test:  shape {y_test.shape} and ndim {y_test.ndim}')

x_train: shape (60000, 28, 28) and ndim 3
x_test:  shape (10000, 28, 28) and ndim 3
y_train: shape (60000,) and ndim 1
y_test:  shape (10000,) and ndim 1


## 4. Preprocessing

The data values are scaled by dividing with 255 to range 0...1. <br>
For the labels are converted to binary class matrix.

In [5]:
x_train = x_train / 255.0 
x_test = x_test / 255.0

y_train = tf.keras.utils.to_categorical(y_train)
y_test = tf.keras.utils.to_categorical(y_test)

## 5. Modeling

We create a Sequential model with different layers and the values from before.First we flatten the input recived from before and later we create 2 layer of densely connected neurons, one layer with the activation function "relu" and the other one with "softmax" function.<br>
And later we compile the model.

In [9]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dense(10, activation='softmax')
])

In [10]:
model.compile(optimizer = 'adam',
              loss = 'categorical_crossentropy',
              metrics = ['accuracy'])

## 6. Training

First I trained the network with 5 epochs to see which accuracy I will get with this epochs, later on I see that I get more accuray than demanded. When I checked the output with 5 epochs, I see that with only 3 epochs we get the accuracy demanded. That's the actual trining with 3 epochs.

In [11]:
model.fit(x_train, y_train, epochs = 3)

Epoch 1/3
1875/1875 [==============================] - 2s 962us/step - loss: 0.2625 - accuracy: 0.9256
Epoch 2/3
1875/1875 [==============================] - 2s 968us/step - loss: 0.1167 - accuracy: 0.9653
Epoch 3/3
1875/1875 [==============================] - 2s 958us/step - loss: 0.0793 - accuracy: 0.9765


## 7. Performance and evaluation

Now we have a model with loss of 0.0899 and accuracy of 0.9733.

In [12]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - loss: 0.0899 - accuracy: 0.9733 - 283ms/epoch - 905us/step


[0.08987543731927872, 0.9732999801635742]

## 8. Discussion and conclusions

As I already explained in the point 6: first I trained the network with 5 epochs, because it was the default configuration, to see which accuracy I will get with this epochs, later on I see that I get more accuray than demanded. When I checked the output with 5 epochs, I see that with only 3 epochs we get the accuracy demanded. That's the actual trining with 3 epochs. <br>
The final model has the next values: 0.0899 loss and an accuracy of 0.9733. <br>
With this first case I learned the basics things and also it let me saw for my self how it works and to test it.

To learn more, see [Tensorflow tutorials](https://www.tensorflow.org/tutorials).